@startuml "http_struct"

' package net{
'    class Socket{
'       std::shared_ptr<int> fd_
'    }
'    class EndPoint
'    class TcpServerSocket{
'       void Bind(int)
'       void Listen(int)
'       TcpClientSocket  *Accept()
'    }
'    class TcpClientSocket{
'       void Send(std::string)
'       std::string Received()
'       void Connect()
'    }

'    interface INetServerSocketAdapter
'    interface INetClientSocketAdapter

'    INetServerSocketAdapter <|-- TcpServerSocket 
'    INetClientSocketAdapter <|-- TcpClientSocket 
'    Socket <-- TcpClientSocket 
'    EndPoint <-- TcpClientSocket 
'    Socket <-- TcpServerSocket 
' }

package http{
   interface Response
   interface Request
   interface Argument
   interface ProtocolHead
   interface ProtocolBody
   
   

   class HttpResponse
   class HttpRequest{
      HttpArugument argument_
      HttpArugument cookie_
      HttpRequestHead head_
      HttpRequestBody body_
      
      HttpArugument url_args_
      HttpArugument post_args_
      const HttpArgument GetCoookies()
   }

   class HttpResponseHead
   class HttpRequestHead

   class HttpResponseBody
   class HttpRequestBody

   class HttpArgument

   HttpArgument --|> Argument

   HttpResponseBody --|> ProtocolBody
   HttpRequestBody  --|> ProtocolBody

   HttpResponseHead --|> ProtocolHead
   HttpRequestHead --|> ProtocolHead

   Response <|-- HttpResponse
   Request  <|-- HttpRequest 


   HttpRequest --> HttpRequestHead
   HttpRequest --> HttpArgument
   HttpRequest --> HttpRequestBody  

   HttpResponse --> HttpResponseHead
   HttpResponse --> HttpArgument
   HttpResponse --> HttpResponseBody

   interface IProtocolObjectFactory

   class HttpProtocolFactory{
      Request *RequestFromString(std::string) override;
      Response *GetResponse();
      IProtocolObjectFactory *GetInstant();
   }


   HttpProtocolFactory --> HttpResponse
   HttpProtocolFactory --> HttpRequest

   IProtocolObjectFactory <|-- HttpProtocolFactory

   class Cookie{
      string name
      string value
      ---暂未确定类型---
      string domain
      string path
      string secure
      string httponly
      string expire
      string time
   }

   HttpResponse --> Cookie
}




@enduml
